<a href="https://colab.research.google.com/github/Vinaypatil-Ev/vinEvPy-GoCoLab/blob/main/Tensorflow/TensorflowPrac11_TPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
+import tensorflow as tf
import os
import tensorflow_datasets as tfds

In [ ]:
cluster = tf.distribute.cluster_resolver.TPUClusterResolver(tpu="grpc://" + os.environ["COLAB_TPU_ADDR"])

In [ ]:
tf.config.experimental_connect_to_cluster(cluster)

In [ ]:
tf.config.list_logical_devices("TPU")

[LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:7', device_type='TPU'),
 LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:6', device_type='TPU'),
 LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:5', device_type='TPU'),
 LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:4', device_type='TPU'),
 LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:3', device_type='TPU'),
 LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:0', device_type='TPU'),
 LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:1', device_type='TPU'),
 LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:2', device_type='TPU')]

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
tf.tpu.experimental.initialize_tpu_system(cluster)
print("All devices: ", tf.config.list_logical_devices('TPU'))

INFO:tensorflow:Initializing the TPU system: grpc://10.85.225.98:8470


INFO:tensorflow:Initializing the TPU system: grpc://10.85.225.98:8470


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


All devices:  [LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:7', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:6', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:5', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:4', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:3', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:0', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:1', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:2', device_type='TPU')]


In [ ]:
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

with tf.device("/TPU:3"):
  c = tf.matmul(a, b)
print("c device: ", c.device)
print(c)

c device:  /job:worker/replica:0/task:0/device:TPU:3
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [ ]:
strategy = tf.distribute.TPUStrategy()

INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


In [ ]:
@tf.function
def matmul_fn(x, y):
  z = tf.matmul(x, y)
  return z

In [ ]:
z = strategy.run(matmul_fn, args=(a, b))
print(z)

PerReplica:{
  0: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  1: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  2: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  3: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  4: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  5: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  6: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  7: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
}


In [ ]:
def mul(x, y):
  return tf.matmul(x, y)


In [ ]:
strategy.run(tf.function(mul), (a, b))

PerReplica:{
  0: <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>,
  2: <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>,
  3: <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>,
  4: <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>,
  5: <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>,
  6: <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>,
  7: <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>
}

In [ ]:
def create_model():
  return tf.keras.Sequential([
                              tf.keras.layers.Conv2D(256, 3, activation="relu", input_shape=(28, 28, 1)),
                              tf.keras.layers.Conv2D(256, 3, activation="relu"),
                              tf.keras.layers.Flatten(),
                              tf.keras.layers.Dense(256, activation="relu"),
                              tf.keras.layers.Dense(256, activation="relu"),
                              tf.keras.layers.Dense(256, activation="relu"),
                              tf.keras.layers.Dense(128, activation="relu"),
                              tf.keras.layers.Dense(10, activation="relu")
  ])

In [ ]:
def get_dataset(batch_size, is_training=True):
  split = "train" if is_training else "test"
  dataset, info = tfds.load("mnist", split=split, with_info=True, as_supervised=True, try_gcs=True)

  def scale(img, label):
    img = tf.cast(img, tf.float32)
    img /= 255.0
    return img, label
  
  dataset = dataset.map(scale)

  if is_training:
    dataset = dataset.shuffle(1000)
    dataset = dataset.repeat()

  dataset = dataset.batch(batch_size)

  return dataset

In [ ]:
def get_dataset(batch_size, is_training=True):
  split = 'train' if is_training else 'test'
  dataset, info = tfds.load(name='mnist', split=split, with_info=True,
                            as_supervised=True, try_gcs=True)

  def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255.0

    return image, label

  dataset = dataset.map(scale)

  # Only shuffle and repeat the dataset in training. The advantage to have a
  # infinite dataset for training is to avoid the potential last partial batch
  # in each epoch, so users don't need to think about scaling the gradients
  # based on the actual batch size.
  if is_training:
    dataset = dataset.shuffle(10000)
    dataset = dataset.repeat()

  dataset = dataset.batch(batch_size)

  return dataset

In [ ]:
with strategy.scope():
  model = create_model()
  model.compile(loss="sparse_categorical_crossentropy", optimizer="adam")

In [ ]:
batch_size = 200
steps_per_epoch = 60000 //batch_size
validation_steps = 10000 //batch_size

In [ ]:
train_dataset = get_dataset(batch_size)
test_dataset = get_dataset(batch_size, is_training=False)


In [ ]:
model.fit(train_dataset,
          epochs=5,
          steps_per_epoch=steps_per_epoch,
          validation_data=test_dataset,
          validation_steps=validation_steps)

Epoch 1/5
300/300 [==============================] - 11s 34ms/step - loss: 0.7008 - sparse_categorical_accuracy: 0.6979 - val_loss: 0.7287 - val_sparse_categorical_accuracy: 0.6982
Epoch 2/5
300/300 [==============================] - 10s 34ms/step - loss: 0.7016 - sparse_categorical_accuracy: 0.6979 - val_loss: 0.7386 - val_sparse_categorical_accuracy: 0.6938
Epoch 3/5
300/300 [==============================] - 11s 35ms/step - loss: 0.7021 - sparse_categorical_accuracy: 0.6977 - val_loss: 0.7357 - val_sparse_categorical_accuracy: 0.6964
Epoch 4/5
300/300 [==============================] - 10s 34ms/step - loss: 0.6981 - sparse_categorical_accuracy: 0.6985 - val_loss: 0.7337 - val_sparse_categorical_accuracy: 0.6954
Epoch 5/5
300/300 [==============================] - 10s 34ms/step - loss: 0.6963 - sparse_categorical_accuracy: 0.6989 - val_loss: 0.7336 - val_sparse_categorical_accuracy: 0.6963


In [ ]:
with strategy.scope():
  model = create_model()
  model.compile(optimizer='adam',
                # Anything between 2 and `steps_per_epoch` could help here.
                experimental_steps_per_execution = 50,
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['sparse_categorical_accuracy'])

model.fit(train_dataset,
          epochs=5,
          steps_per_epoch=steps_per_epoch,
          validation_data=test_dataset,
          validation_steps=validation_steps)

Epoch 1/5
300/300 [==============================] - 16s 52ms/step - loss: 0.4057 - sparse_categorical_accuracy: 0.8680 - val_loss: 0.0493 - val_sparse_categorical_accuracy: 0.9839
Epoch 2/5
300/300 [==============================] - 5s 17ms/step - loss: 0.0463 - sparse_categorical_accuracy: 0.9861 - val_loss: 0.0390 - val_sparse_categorical_accuracy: 0.9872
Epoch 3/5
300/300 [==============================] - 5s 17ms/step - loss: 0.0272 - sparse_categorical_accuracy: 0.9921 - val_loss: 0.0440 - val_sparse_categorical_accuracy: 0.9864
Epoch 4/5
300/300 [==============================] - 5s 17ms/step - loss: 0.0197 - sparse_categorical_accuracy: 0.9941 - val_loss: 0.0497 - val_sparse_categorical_accuracy: 0.9871
Epoch 5/5
300/300 [==============================] - 5s 17ms/step - loss: 0.0151 - sparse_categorical_accuracy: 0.9956 - val_loss: 0.0428 - val_sparse_categorical_accuracy: 0.9889


In [ ]:
with strategy.scope():
  model = create_model()
  optimizer = tf.keras.optimizers.Adam()
  training_loss = tf.keras.metrics.Mean("training_loss", dtype=tf.float32)
  training_accuracy = tf.keras.metrics.SparseCategoricalAccuracy("training_accuracy", tf.float32)

per_replica_batch_size = batch_size // strategy.num_replicas_in_sync

train_dataset = strategy.distribute_datasets_from_function(
    lambda _: get_dataset(per_replica_batch_size, is_training=True)
)

@tf.function
def train_fun(iterator):
  def gradient_fun(inputs):
    img, labels = inputs
    with tf.GradientTape() as tape:
      logits = model(img, training=True)
      loss = tf.keras.losses.sparse_categorical_crossentropy(
          labels, logits, from_logits=True,
      )
      loss = tf.nn.compute_average_loss(loss, global_batch_size=batch_size)
    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(list(zip(grads, model.trainable_variables)))
    training_loss.update_state(loss * strategy.num_replicas_in_sync)
    training_accuracy.update_state(labels, logits)
  strategy.run(gradient_fun, args=(next(iterator), ))

In [ ]:
strategy.num_replicas_in_sync

8

In [ ]:
steps_per_eval = 10000 // batch_size

train_iterator = iter(train_dataset)

for epoch in range(5):
  print(f"epochs: {epoch}/5")
  for step in range(steps_per_epoch):
    train_fun(train_iterator)
  print(f"current_step: {optimizer.iterations.numpy()}, \
          training_loss: {round(float(training_loss.result()), 2)}, \
          accuracy : {round(float(training_accuracy.result() * 100), 2)},\
              ")
  training_loss.reset_states()
  training_accuracy.reset_states()

epochs: 0/5
current_step: 3900,           training_loss: 0.24,           accuracy : 89.89,              
epochs: 1/5
current_step: 4200,           training_loss: 0.23,           accuracy : 90.0,              
epochs: 2/5
current_step: 4500,           training_loss: 0.23,           accuracy : 89.97,              
epochs: 3/5
current_step: 4800,           training_loss: 0.23,           accuracy : 89.93,              
epochs: 4/5
current_step: 5100,           training_loss: 0.23,           accuracy : 89.99,              


In [ ]:
class CustomModel(tf.keras.models.Model):

  @tf.function
  def call(self, input_data):
    if tf.reduce_mean(input_data) > 0:
      return input_data
    else:
      import pdb
      pdb.set_trace()
      
      return input_data // 2


tf.config.experimental_run_functions_eagerly(True)
model = CustomModel()
model(tf.constant([-2, -4]))

--KeyboardInterrupt--
--KeyboardInterrupt--
--KeyboardInterrupt--
--KeyboardInterrupt--
--KeyboardInterrupt--


In [ ]:
54
4