<a href="https://colab.research.google.com/github/Vinaypatil-Ev/vinEvPy-GoCoLab/blob/main/Tensorflow/TensorflowPrac16_SaveModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np

# Save and Load Models

## create simple model

In [ ]:
def get_model():
    inputs = tf.keras.Input((32,))
    outputs = tf.keras.layers.Dense(1, activation="relu")(inputs)
    model = tf.keras.Model(inputs, outputs)
    model.compile(optimizer="adam", loss="mse")
    return model

In [ ]:
model = get_model()

In [ ]:
input_data = np.random.random((128, 32))
output_data = np.random.random((128, 1))
model.fit(input_data, output_data)

4/4 [==============================] - 0s 3ms/step - loss: 0.2135


## Saving above model

In [ ]:
model.save("saved_model123")

INFO:tensorflow:Assets written to: saved_model123/assets


### save as **.h5** model(keras way)

In [ ]:
model.save("saved_model11.keras")

In [ ]:
model.save("saved_model12.h5")

In [ ]:
!ls

sample_data  saved_model11.keras  saved_model123  saved_model12.h5


# load saved model

In [ ]:
saved_model = tf.keras.models.load_model("saved_model123")

In [ ]:
saved_model.predict(input_data[:5])

array([[0.9347816 ],
       [0.17120656],
       [0.5414269 ],
       [0.15207213],
       [0.41472995]], dtype=float32)

In [ ]:
model.predict(input_data[:5])

array([[0.9347816 ],
       [0.17120656],
       [0.5414269 ],
       [0.15207213],
       [0.41472995]], dtype=float32)

## How saved model handles custom format

### It is neccessary to define get_config() and from_config() for custom models and layers

### Lets see what happenes with config method


###1.*getconfig()* 
###2. *from_config()* 
###3. *to_json()* 
###4. *tf.keras.models.model_from_json()*

In [ ]:
class CustomModel(tf.keras.Model):
    def __init__(self, dense_list):
        super(CustomModel, self).__init__()
        self.dense_layers = [tf.keras.layers.Dense(o) for o in dense_list]
    
    def call(self, inputs):
        x = inputs
        for layers in self.dense_layers:
            x = layers(x)
        return x

In [ ]:
model = CustomModel([64, 64, 64, 1])
input_data = np.random.random((1, 5))

In [ ]:
outputs = model(input_data)
outputs

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.15760417]], dtype=float32)>

In [ ]:
mp = "check_saved_model"
model.save(mp)

INFO:tensorflow:Assets written to: check_saved_model/assets


In [ ]:
del CustomModel
model123 = tf.keras.models.load_model(mp)

In [ ]:
model123(input_data)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.15760417]], dtype=float32)>

## loder create model that acts like original model

In [ ]:
model

In [ ]:
model123

## Creating layers and models from configuration



###1 Layers

In [ ]:
import pprint

In [ ]:
layer = tf.keras.layers.Dense(64, activation="relu")
layer_config = layer.get_config()
generated_layer = tf.keras.layers.Dense.from_config(layer_config)

In [ ]:
pprint.pprint(layer_config)

{'activation': 'relu',
 'activity_regularizer': None,
 'bias_constraint': None,
 'bias_initializer': {'class_name': 'Zeros', 'config': {}},
 'bias_regularizer': None,
 'dtype': 'float32',
 'kernel_constraint': None,
 'kernel_initializer': {'class_name': 'GlorotUniform',
                        'config': {'seed': None}},
 'kernel_regularizer': None,
 'name': 'dense_43',
 'trainable': True,
 'units': 64,
 'use_bias': True}


###2 Sequential Model

In [ ]:
smodel = tf.keras.Sequential([tf.keras.layers.Dense(64)])
smodel_config = smodel.get_config()
smodelc = tf.keras.Sequential.from_config(smodel_config)
smodelc

In [ ]:
pprint.pprint(smodel_config)

{'layers': [{'class_name': 'Dense',
             'config': {'activation': 'linear',
                        'activity_regularizer': None,
                        'bias_constraint': None,
                        'bias_initializer': {'class_name': 'Zeros',
                                             'config': {}},
                        'bias_regularizer': None,
                        'dtype': 'float32',
                        'kernel_constraint': None,
                        'kernel_initializer': {'class_name': 'GlorotUniform',
                                               'config': {'seed': None}},
                        'kernel_regularizer': None,
                        'name': 'dense_44',
                        'trainable': True,
                        'units': 64,
                        'use_bias': True}}],
 'name': 'sequential'}


###3. Funtional API

In [ ]:
inputs = tf.keras.Input((32,))
outputs = tf.keras.layers.Dense(64, activation="relu")(inputs)
fmodel = tf.keras.Model(inputs, outputs)
fmodel_config = fmodel.get_config()
fomdelc = tf.keras.Model.from_config(fmodel_config)

In [ ]:
pprint.pprint(fmodel_config)

{'input_layers': [['input_2', 0, 0]],
 'layers': [{'class_name': 'InputLayer',
             'config': {'batch_input_shape': (None, 32),
                        'dtype': 'float32',
                        'name': 'input_2',
                        'ragged': False,
                        'sparse': False},
             'inbound_nodes': [],
             'name': 'input_2'},
            {'class_name': 'Dense',
             'config': {'activation': 'relu',
                        'activity_regularizer': None,
                        'bias_constraint': None,
                        'bias_initializer': {'class_name': 'Zeros',
                                             'config': {}},
                        'bias_regularizer': None,
                        'dtype': 'float32',
                        'kernel_constraint': None,
                        'kernel_initializer': {'class_name': 'GlorotUniform',
                                               'config': {'seed': None}},
                 

### Similary to *to_config()* *and from_config()* , we can use *get_json()* *and from_json()*

In [ ]:
smodel1 = tf.keras.Sequential([tf.keras.layers.Dense(64)])
smodel_json = smodel1.to_json()
smodel1c = tf.keras.models.model_from_json(smodel_json)

In [ ]:
pprint.pprint(smodel_json)

('{"class_name": "Sequential", "config": {"name": "sequential_6", "layers": '
 '[{"class_name": "Dense", "config": {"name": "dense_51", "trainable": true, '
 '"dtype": "float32", "units": 64, "activation": "linear", "use_bias": true, '
 '"kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": '
 'null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, '
 '"kernel_regularizer": null, "bias_regularizer": null, '
 '"activity_regularizer": null, "kernel_constraint": null, "bias_constraint": '
 'null}}]}, "keras_version": "2.4.0", "backend": "tensorflow"}')


###4. custom_layers()

In [ ]:
class CustomLayer(tf.keras.layers.Layer):
    def __init__(self, x):
        self.x = tf.Variable(x)
    def call(self, inputs):
        return inputs * self.x
    
    def get_config(self):
        return {"x": self.x.numpy()}
    
    @classmethod
    def from_config(cls, config):
        return cls(**config)

### Serializing custom layers

####1. Serialize

In [ ]:
layer = CustomLayer(5)
serialized_layer = tf.keras.layers.serialize(layer)
serialized_layer

{'class_name': 'CustomLayer', 'config': {'x': 5}}

####2.deserialize

In [ ]:
deserialized_layer = tf.keras.layers.deserialize(
    serialized_layer, custom_objects={"CustomLayer": CustomLayer}
)

In [ ]:
deserialized_layer

In [ ]:
layer

## Custom layer and Function

### *tf.keras.utils.custom_object_scope* and *tf.keras.utils.CustomObjectsScope*
### *tf.keras.regester_keras_serializable*

In [ ]:
class CustomLayer(tf.keras.layers.Layer):
    def __init__(self,units, **kwargs):
        super(CustomLayer, self).__init__(**kwargs)
        self.units = units
    
    def build(self, input_shape):
        self.w = self.add_weight(shape=(input_shape[-1], self.units), initializer="random_normal", trainable=True)
        self.b = self.add_weight(shape=(self.units), initializer="zeros", trainable=True)

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b
    
    def get_config(self):
        config = super().get_config()
        config.update({"units": self.units})
        return config

In [ ]:
def CustomActivation(inputs):
    return tf.nn.relu(inputs)


In [ ]:
inputs = tf.keras.Input((32,))
x = CustomLayer(32)(inputs)
outputs = tf.keras.layers.Activation(CustomActivation)(x)
model = tf.keras.Model(inputs, outputs)

In [ ]:
custom_object = {"CustomLayer": CustomLayer,  "CustomActivation": CustomActivaion}
with tf.keras.utils.custom_object_scope(custom_object):
    new_model = tf.keras.Model.from_config(model.get_config())

### also you can do memory clonning

In [ ]:
with tf.keras.utils.custom_object_scope(custom_object):
    new_model1 = tf.keras.models.clone_model(model)

In [ ]:
new_model

In [ ]:
new_model1

## Saving and Loading only weights of model

### We choose this step when:
####1. You only need model for inference; not compilation information and optimizer state
####2. You are doing transfere learning: training of model using weights of prebuilt model

### Saving loading weight API
####1. *get_weight()*
####2. *set_weight()*

## Transferring Weights from:

###1. Layers to Layer



In [ ]:
layer = tf.keras.layers.Dense(64, activation="relu")
